-- Products + transactions for the vending machine bridge (sync/machine_supabase_bridge.py).
-- Run once in Supabase → SQL Editor (adjust names only if you already diverged).

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slot_number integer not null unique,
  name text not null,
  details text,
  price numeric not null,
  capacity integer not null,
  current_stock integer not null,
  updated_at timestamptz not null default now()
);

create index if not exists products_slot_number_idx on public.products (slot_number);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  -- Stable id from the machine's local SQLite `transactions.id` (enables safe upserts / replays)
  source_tx_id bigint unique,
  created_at timestamptz not null default now(),
  product_id bigint,
  product_name text,
  slot_number integer,
  quantity integer,
  total_amount numeric,
  payment_method text,
  rfid_user_id bigint
);

create index if not exists transactions_created_at_idx on public.transactions (created_at desc);
create unique index if not exists transactions_source_tx_id_ux on public.transactions (source_tx_id);

-- Backwards-compatible migration (if the table already exists)
alter table public.transactions
  add column if not exists source_tx_id bigint;
create unique index if not exists transactions_source_tx_id_ux on public.transactions (source_tx_id);

-- ---------- Automatic duplicate cleanup ----------
-- If duplicates were inserted before `source_tx_id` existed (or before the index was added),
-- this trigger removes duplicates as new rows arrive. It keeps the *earliest* row per key.
-- Key priority:
--   1) source_tx_id (best, stable from the machine)
--   2) fallback "fingerprint" based on the main sale fields (only when source_tx_id is NULL)

create or replace function public.tr_dedupe_transactions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  keep_id bigint;
begin
  if new.source_tx_id is not null then
    select min(id) into keep_id from public.transactions where source_tx_id = new.source_tx_id;
    delete from public.transactions
    where source_tx_id = new.source_tx_id
      and id <> keep_id;
    return new;
  end if;

  -- Fallback fingerprint (only for rows without source_tx_id)
  select min(id) into keep_id
  from public.transactions
  where source_tx_id is null
    and created_at = new.created_at
    and product_id is not distinct from new.product_id
    and product_name is not distinct from new.product_name
    and slot_number is not distinct from new.slot_number
    and quantity is not distinct from new.quantity
    and total_amount is not distinct from new.total_amount
    and payment_method is not distinct from new.payment_method
    and rfid_user_id is not distinct from new.rfid_user_id;

  delete from public.transactions
  where source_tx_id is null
    and created_at = new.created_at
    and product_id is not distinct from new.product_id
    and product_name is not distinct from new.product_name
    and slot_number is not distinct from new.slot_number
    and quantity is not distinct from new.quantity
    and total_amount is not distinct from new.total_amount
    and payment_method is not distinct from new.payment_method
    and rfid_user_id is not distinct from new.rfid_user_id
    and id <> keep_id;

  return new;
end;
$$;

drop trigger if exists tr_transactions_dedupe on public.transactions;
create trigger tr_transactions_dedupe
  after insert on public.transactions
  for each row
  execute function public.tr_dedupe_transactions();

-- One-time cleanup you can run manually (safe to re-run). Useful after enabling source_tx_id:
-- with ranked as (
--   select id, row_number() over (
--     partition by coalesce(source_tx_id::text, concat_ws('|',
--       created_at::text, product_id::text, product_name, slot_number::text,
--       quantity::text, total_amount::text, payment_method, rfid_user_id::text
--     ))
--     order by id
--   ) as rn
--   from public.transactions
-- )
-- delete from public.transactions t using ranked r
-- where t.id = r.id and r.rn > 1;

alter table public.products enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "products_select_dashboard" on public.products;
create policy "products_select_dashboard"
  on public.products for select
  to anon, authenticated
  using (true);

drop policy if exists "transactions_select_dashboard" on public.transactions;
create policy "transactions_select_dashboard"
  on public.transactions for select
  to anon, authenticated
  using (true);

-- Inserts use service_role from the Pi (bypasses RLS). Do not expose service_role in the browser.

-- Realtime: replicate INSERT/UPDATE/DELETE to subscribed browsers
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'products'
  ) then
    alter publication supabase_realtime add table public.products;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'transactions'
  ) then
    alter publication supabase_realtime add table public.transactions;
  end if;
end $$;

-- ---------- Optional: live_feed dedupe (prevents repeated feed spam) ----------
-- Requires public.live_feed to exist (run WebSite/supabase/machine_live_feed.sql first).
-- Dedupes by payload.source_tx_id (best) or payload.transaction_id; otherwise uses a fallback fingerprint.

create or replace function public.tr_dedupe_live_feed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  keep_id bigint;
  k text;
begin
  -- Prefer stable transaction id from payload.
  k := nullif(trim(coalesce(new.payload->>'source_tx_id', new.payload->>'transaction_id', '')), '');
  if k is not null then
    select min(id) into keep_id
    from public.live_feed
    where coalesce(payload->>'source_tx_id', payload->>'transaction_id') = k;

    delete from public.live_feed
    where coalesce(payload->>'source_tx_id', payload->>'transaction_id') = k
      and id <> keep_id;
    return new;
  end if;

  -- Fallback fingerprint (only when payload doesn't include a stable transaction id).
  select min(id) into keep_id
  from public.live_feed
  where created_at = new.created_at
    and event_type is not distinct from new.event_type
    and message is not distinct from new.message
    and quantity is not distinct from new.quantity
    and total_amount is not distinct from new.total_amount;

  delete from public.live_feed
  where created_at = new.created_at
    and event_type is not distinct from new.event_type
    and message is not distinct from new.message
    and quantity is not distinct from new.quantity
    and total_amount is not distinct from new.total_amount
    and id <> keep_id;

  return new;
end;
$$;

do $$
begin
  if to_regclass('public.live_feed') is not null then
    drop trigger if exists tr_live_feed_dedupe on public.live_feed;
    create trigger tr_live_feed_dedupe
      after insert on public.live_feed
      for each row
      execute function public.tr_dedupe_live_feed();
  end if;
end $$;
