-- Products + transactions for the vending machine bridge (sync/machine_supabase_bridge.py).
-- Run once in Supabase → SQL Editor (adjust names only if you already diverged).

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slot_number integer not null unique,
  name text not null,
  details text,
  price numeric not null,
  capacity integer not null,
  current_stock integer not null,
  updated_at timestamptz not null default now()
);

create index if not exists products_slot_number_idx on public.products (slot_number);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id bigint,
  product_name text,
  slot_number integer,
  quantity integer,
  total_amount numeric,
  payment_method text,
  rfid_user_id bigint
);

create index if not exists transactions_created_at_idx on public.transactions (created_at desc);

alter table public.products enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "products_select_dashboard" on public.products;
create policy "products_select_dashboard"
  on public.products for select
  to anon, authenticated
  using (true);

drop policy if exists "transactions_select_dashboard" on public.transactions;
create policy "transactions_select_dashboard"
  on public.transactions for select
  to anon, authenticated
  using (true);

-- Inserts use service_role from the Pi (bypasses RLS). Do not expose service_role in the browser.

-- Realtime: replicate INSERT/UPDATE/DELETE to subscribed browsers
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'products'
  ) then
    alter publication supabase_realtime add table public.products;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'transactions'
  ) then
    alter publication supabase_realtime add table public.transactions;
  end if;
end $$;
