-- Supabase schema for realtime sync between machine (SQLite) and website.
-- Run this in Supabase SQL Editor.

-- PRODUCTS
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slot_number int not null unique,
  name text not null,
  details text,
  price numeric not null,
  capacity int not null default 10,
  current_stock int not null default 0,
  updated_at timestamptz not null default now()
);

-- TRANSACTIONS
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id bigint,
  product_name text,
  slot_number int,
  quantity int,
  total_amount numeric,
  payment_method text,
  rfid_user_id bigint
);

-- Enable Realtime on these tables in Supabase UI (Database → Replication):
-- or via SQL (works on many Postgres setups):
alter table public.products replica identity full;
alter table public.transactions replica identity full;

