-- Run in Supabase -> SQL Editor.
-- Bug reports submitted from the machine (main.py -> bugreport.py) can be viewed in the website dashboard in realtime.

create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp_ms bigint,
  machine_id text,
  version text,
  theme text,
  category text not null,
  details text,
  status text not null default 'open',
  fixed_at timestamptz,
  fixed_by text
);

-- Backwards-compatible migration if the table already existed before new columns were added
alter table public.bug_reports
  add column if not exists status text;
alter table public.bug_reports
  alter column status set default 'open';
update public.bug_reports set status = 'open' where status is null;
alter table public.bug_reports
  alter column status set not null;

alter table public.bug_reports
  add column if not exists fixed_at timestamptz;
alter table public.bug_reports
  add column if not exists fixed_by text;

create index if not exists bug_reports_created_at_idx on public.bug_reports (created_at desc);

alter table public.bug_reports enable row level security;

drop policy if exists "bug_reports_select_dashboard" on public.bug_reports;
create policy "bug_reports_select_dashboard"
  on public.bug_reports for select
  to anon, authenticated
  using (true);

-- Allow dashboard to mark reports as fixed (simple thesis-friendly policy).
drop policy if exists "bug_reports_update_dashboard" on public.bug_reports;
create policy "bug_reports_update_dashboard"
  on public.bug_reports for update
  to anon, authenticated
  using (true)
  with check (true);

-- Inserts should come from service_role (machine), so we don't allow anon inserts here.

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bug_reports'
  ) then
    alter publication supabase_realtime add table public.bug_reports;
  end if;
end $$;

-- Refresh PostgREST schema cache so new columns are usable immediately
notify pgrst, 'reload schema';

