-- Run in Supabase -> SQL Editor.
-- Bug reports submitted from the machine (main.py -> bugreport.py) can be viewed in the website dashboard in realtime.

create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  timestamp_ms bigint,
  machine_id text,
  ticket_number text,
  email text,
  version text,
  theme text,
  category text not null,
  details text,
  status text not null default 'open',
  fixed_at timestamptz,
  fixed_by text
);

-- Backwards-compatible migration if the table already existed before new columns were added
alter table public.bug_reports
  add column if not exists ticket_number text;
alter table public.bug_reports
  add column if not exists email text;

-- Ticket numbers should be unique when present
do $$
begin
  if not exists (
    select 1 from pg_indexes
    where schemaname = 'public' and indexname = 'bug_reports_ticket_number_key'
  ) then
    create unique index bug_reports_ticket_number_key on public.bug_reports (ticket_number) where ticket_number is not null;
  end if;
end $$;

alter table public.bug_reports
  add column if not exists status text;
alter table public.bug_reports
  alter column status set default 'open';
update public.bug_reports set status = 'open' where status is null;
alter table public.bug_reports
  alter column status set not null;

alter table public.bug_reports
  add column if not exists fixed_at timestamptz;
alter table public.bug_reports
  add column if not exists fixed_by text;

create index if not exists bug_reports_created_at_idx on public.bug_reports (created_at desc);

alter table public.bug_reports enable row level security;

drop policy if exists "bug_reports_select_dashboard" on public.bug_reports;
create policy "bug_reports_select_dashboard"
  on public.bug_reports for select
  to anon, authenticated
  using (true);

-- Allow dashboard to mark reports as fixed (simple thesis-friendly policy).
drop policy if exists "bug_reports_update_dashboard" on public.bug_reports;
create policy "bug_reports_update_dashboard"
  on public.bug_reports for update
  to anon, authenticated
  using (true)
  with check (true);

-- Inserts should come from service_role (machine), so we don't allow anon inserts here.

-- Store reporter emails in a separate table for easy export/updates
create table if not exists public.bug_report_emails (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null unique
);

alter table public.bug_report_emails enable row level security;
drop policy if exists "bug_report_emails_select_dashboard" on public.bug_report_emails;
create policy "bug_report_emails_select_dashboard"
  on public.bug_report_emails for select
  to anon, authenticated
  using (true);

-- Trigger: capture email on each bug report insert (ignore duplicates)
create or replace function public.capture_bug_report_email()
returns trigger
language plpgsql
as $$
begin
  if new.email is not null and length(trim(new.email)) > 0 then
    insert into public.bug_report_emails(email)
    values (trim(new.email))
    on conflict (email) do nothing;
  end if;
  return new;
end $$;

drop trigger if exists bug_reports_capture_email on public.bug_reports;
create trigger bug_reports_capture_email
after insert on public.bug_reports
for each row execute function public.capture_bug_report_email();

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bug_reports'
  ) then
    alter publication supabase_realtime add table public.bug_reports;
  end if;
end $$;

-- Refresh PostgREST schema cache so new columns are usable immediately
notify pgrst, 'reload schema';

