-- Append-style script: safe to run in Supabase SQL Editor.
-- live_feed = append-only activity from the vending machine for the admin website (REST + Realtime).
--
-- Example from machine / SQL:
--   insert into public.live_feed (event_type, message, payload)
--   values ('sale', 'Dispensed Hand Sanitizer slot 3', '{"slot":3}'::jsonb);
--
-- First-time setup / empty table: run supabase/live_feed_seed_and_trigger.sql for demo rows
-- and an optional trigger that copies new rows from public.transactions into live_feed.

create table if not exists public.live_feed (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null default 'info',
  message text not null,
  payload jsonb default '{}'::jsonb
);

create index if not exists live_feed_created_at_idx on public.live_feed (created_at desc);

alter table public.live_feed enable row level security;

drop policy if exists "live_feed_select_anon" on public.live_feed;
create policy "live_feed_select_anon"
  on public.live_feed for select
  to anon, authenticated
  using (true);

drop policy if exists "live_feed_insert_anon" on public.live_feed;
create policy "live_feed_insert_anon"
  on public.live_feed for insert
  to anon, authenticated
  with check (char_length(trim(message)) > 0);

-- Realtime (also enable table under Database → Replication if needed)
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'live_feed'
  ) then
    alter publication supabase_realtime add table public.live_feed;
  end if;
end $$;
